name: Bug Report
description: This is the form if you encounter bugs somewhere in Lebirun. (Some Bugs may be features OR its not a problem in code)
title: "[BUG]: "
labels: ["Bug"]
body:
  - type: textarea
    id: issue
    attributes:
      label: What issue are you encountering?
      description: What did you expect to happen?
      placeholder: Your Bug Here
    validations:
      required: true
  - type: dropdown
    id: os_ver
    attributes:
      label: OS Version
      description: Which Lebirun Version are you running?
      options:
        - Lebirun 0.1.0 Alpha 1
        - Lebirun 0.1.0 Alpha 2
      default: 0
    validations:
      required: true
