name: Bug Report
description: This is the form if you encounter bugs somewhere in Lebirun. (Some Bugs may be features OR its not a problem in code)
title: "[BUG]: "
label: ["Bug"]
body:
  - type: textarea
    id: issue
    attributes:
      label: What issue are you encountering?
      description: Tell us also what did you expect to happen.
      placeholder: Your Bug Here
    validations:
      required: true
  - type: dropdown
    id: os_ver
    attributes:
      label: Which Lebirun Version are you running?
      description: The Newest version is recommended for a bit easier bug fixing
      options:
        - Lebirun 0.1.0 Alpha 1
        - Lebirun 0.1.0 Alpha 2
      default: 0
    validations:
      required: true
  - type: checkboxes
    id: accept
    attributes:
      label: "Please review the text you typed in the textboxes and the Lebirun Version, and then you're ready to check the checkmark and submit the bug report!"
      description: You're ready to submit a bug report after you checked this!
      options:
        - label: 
          required: true
