name: Bug Report
description: This is the form if you encounter bugs somewhere in Lebirun. (Some Bugs may be features OR its not a problem in code)
title: "[BUG]: "
labels: ["Bug"]
body:
  - type: textarea
    id: issue
    attributes:
      label: What issue are you encountering?
      description: What did you expect to happen?
      placeholder: Your Bug Here
    validations:
      required: true
