blank_issues_enabled: false
contact_links:
  - name: Official Website
    url: https://lebirun.000.pe/
    about: Official Lebirun Website!
  - name: Lebirun Downloads Website
    url: https://download.lebirun.000.pe/
    about: Official Lebirun Website for downloading ISO and other things!
