name: Feature Request
description: Request a feature
title: "[FEATURE REQUEST]: "
labels: ["Feature Request"]
body:
  - type: textarea
    id: feature-main
    attributes:
      label: Type everything you want about the feature here!
      placeholder: Feature Text Here
    validations:
      required: true
